# Arquivo: docker-compose.yml
version: "3.8"

services:
  app:
    # Constrói a imagem usando o Dockerfile no diretório atual
    build: .

    # Nome do container que será criado
    container_name: automobile_app

    # Mapeia a porta 5000 do seu computador para a 5000 do container
    ports:
      - "5001:5000"

    # Define variáveis de ambiente para o container
    environment:
      - PORT=5000

    # Cria e anexa um volume para persistir os dados da sessão do SQLite.
    volumes:
      - session_data:/usr/src/app/config

# Define os volumes que serão gerenciados pelo Docker
volumes:
  session_data:
