# Arquivo: docker-compose.yml
services:
  app:
    # Constrói a imagem usando o Dockerfile no diretório atual
    build: .

    # Nome do container que será criado
    container_name: automobile_app

    # Mapeia a porta 5000 do seu computador para a 5000 do container
    ports:
      - "${PUBLIC_PORT}:${INTERNAL_PORT}"

    # Esta diretiva carrega todas as variáveis do .env para dentro do container
    env_file:
      - .env
      
    # Cria e anexa um volume para persistir os dados da sessão do SQLite.
    volumes:
      - session_data:/usr/src/app/config

# Define os volumes que serão gerenciados pelo Docker
volumes:
  session_data:
